# Generated by Django 4.2.1 on 2023-06-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='servings',
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='thumbnail',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='video_link',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
