# Generated by Django 4.2.1 on 2023-06-09 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_recipe_servings_recipe_source_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.day'),
        ),
    ]
