# Generated by Django 4.2.1 on 2023-06-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_recipe_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='idMeal',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
